### ISSUE TITLE
Interrupt and write EEPROM

### ISSUE THREAD

**Issue by Beavisgood** [PRosenb/EEPROMWearLevel#4]
Hello!
Thank you for you library EEPROMWearLevel, it's really usefull.
I have one problem, when I use EEPROMwl.put function, Timer1 stop short time, 
but and I have some problem.
Can I fix it?

**Comment by PRosenb** [comment]
Hi @Beavisgood , great to hear is the library useful for you.
Are you calling `EPROMwl.put()` from an interrupt?

**Comment by Beavisgood** [comment]
No, I calling it just in main cyrcle.

**Comment by PRosenb** [comment]
I see..
Generally, the library is based on the Arduino Library `EEPROM Library` including its limitations (except wear levelling).
https://www.arduino.cc/en/Reference/EEPROM

Could you test if it also happens when you use `EEPROM Library` directly, without `EEPROMWearLevel`? Instead of `EEPROMwl.put()` use `EEPROM.put()`.

What do you mean with "Timer1 stop short time"?
Do you use an interrupt that is delayed when you do `EPROMwl.put()`? Or do you control an output PIN that becomes delayed?
